spring.application.name=smartcampus

server.port=8086

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI}

# Google OAuth
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email